#!/usr/bin/env node
/**
 * Syncs the self-hosted webfonts from the @fontsource packages into public/fonts/
 * and regenerates src/styles/fonts.css with matching @font-face rules.
 *
 * Only the weights the design system actually uses are shipped (MASTER.md §4):
 *   Inter            400 / 500 / 600 / 700           (normal)
 *   Barlow Condensed 600 / 700 / 800 normal + 700 italic
 * in the latin and latin-ext subsets (squad names carry diacritics).
 *
 * Run after upgrading @fontsource/*:  node scripts/sync-fonts.mjs
 */
import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outDir = join(root, 'public', 'fonts')
const cssOut = join(root, 'src', 'styles', 'fonts.css')

const WANTED = [
  { pkg: '@fontsource/inter', family: 'Inter', subsets: ['latin', 'latin-ext'], faces: [
    { weight: 400, style: 'normal' },
    { weight: 500, style: 'normal' },
    { weight: 600, style: 'normal' },
    { weight: 700, style: 'normal' },
  ] },
  { pkg: '@fontsource/barlow-condensed', family: 'Barlow Condensed', subsets: ['latin', 'latin-ext'], faces: [
    { weight: 600, style: 'normal' },
    { weight: 700, style: 'normal' },
    { weight: 700, style: 'italic' },
    { weight: 800, style: 'normal' },
  ] },
]

/** Pull the unicode-range for a subset out of the package's per-weight CSS. */
function unicodeRange(pkgDir, slug, subset, weight, style) {
  const cssFile = join(pkgDir, style === 'italic' ? `${weight}-italic.css` : `${weight}.css`)
  const css = readFileSync(cssFile, 'utf8')
  const marker = `/* ${slug}-${subset}-${weight}-${style} */`
  const block = css.slice(css.indexOf(marker))
  const match = block.match(/unicode-range:\s*([^;]+);/)
  if (!match) throw new Error(`No unicode-range for ${slug} ${subset} ${weight} ${style}`)
  return match[1].trim()
}

mkdirSync(outDir, { recursive: true })

let css = `/* Generated by scripts/sync-fonts.mjs — do not edit by hand. */\n`
let copied = 0

for (const { pkg, family, subsets, faces } of WANTED) {
  const pkgDir = join(root, 'node_modules', pkg)
  const slug = pkg.split('/')[1]
  for (const { weight, style } of faces) {
    for (const subset of subsets) {
      const file = `${slug}-${subset}-${weight}-${style}.woff2`
      copyFileSync(join(pkgDir, 'files', file), join(outDir, file))
      copied += 1
      css += `
@font-face {
  font-family: '${family}';
  font-style: ${style};
  font-display: swap;
  font-weight: ${weight};
  src: url(/fonts/${file}) format('woff2');
  unicode-range: ${unicodeRange(pkgDir, slug, subset, weight, style)};
}
`
    }
  }
}

mkdirSync(dirname(cssOut), { recursive: true })
writeFileSync(cssOut, css)
console.log(`Copied ${copied} woff2 files to public/fonts/ and wrote ${cssOut}`)
