// <auto-generated />
using System;
using FcDraft.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FcDraft.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FcDraftDbContext))]
    [Migration("20260716020240_AddDraftPicks")]
    partial class AddDraftPicks
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FcDraft.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_version_id");

                    b.Property<bool>("IsFiveStarEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_five_star_eligible");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("league");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int?>("StarRating")
                        .HasColumnType("integer")
                        .HasColumnName("star_rating");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_clubs_version_name");

                    b.ToTable("clubs", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DatasetImportIssue", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_version_id");

                    b.Property<int?>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<string>("Field")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("field");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("message");

                    b.Property<int>("Row")
                        .HasColumnType("integer")
                        .HasColumnName("row");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("severity");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId")
                        .HasDatabaseName("ix_dataset_import_issues_version");

                    b.ToTable("dataset_import_issues", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.Draft", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("code");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Format")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("format");

                    b.Property<Guid>("HostUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("host_user_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("PickTimerSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("pick_timer_seconds");

                    b.Property<Guid?>("PinnedDatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("pinned_dataset_version_id");

                    b.Property<Guid>("RosterTemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("roster_template_id");

                    b.Property<DateTimeOffset?>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_drafts_code");

                    b.HasIndex("HostUserId")
                        .HasDatabaseName("ix_drafts_host_user_id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_drafts_status");

                    b.ToTable("drafts", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ActorUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("actor_user_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<string>("FromStatus")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("from_status");

                    b.Property<string>("Payload")
                        .HasColumnType("text")
                        .HasColumnName("payload");

                    b.Property<string>("Reason")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("reason");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.Property<string>("ToStatus")
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("to_status");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_events_draft_sequence");

                    b.ToTable("draft_events", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<bool>("IsHost")
                        .HasColumnType("boolean")
                        .HasColumnName("is_host");

                    b.Property<bool>("IsReady")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ready");

                    b.Property<string>("Seed")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("seed");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "UserId")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_participants_draft_user");

                    b.ToTable("draft_participants", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftPick", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<Guid>("DraftTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_team_id");

                    b.Property<int>("FootballerId")
                        .HasColumnType("integer")
                        .HasColumnName("footballer_id");

                    b.Property<string>("FootballerName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("footballer_name");

                    b.Property<int>("FootballerOverall")
                        .HasColumnType("integer")
                        .HasColumnName("footballer_overall");

                    b.Property<string>("FootballerPosition")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("footballer_position");

                    b.Property<Guid?>("PickedByParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("picked_by_participant_id");

                    b.Property<int>("SlotOrder")
                        .HasColumnType("integer")
                        .HasColumnName("slot_order");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "FootballerId")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_picks_draft_footballer");

                    b.HasIndex("DraftTeamId", "SlotOrder")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_picks_team_slot");

                    b.ToTable("draft_picks", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftRosterSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("slot_order");

                    b.Property<string>("Position")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("position");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("slot_type");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_roster_slots_draft_order");

                    b.ToTable("draft_roster_slots", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SelectedClubId")
                        .HasColumnType("uuid")
                        .HasColumnName("selected_club_id");

                    b.Property<int?>("SpinnerRank")
                        .HasColumnType("integer")
                        .HasColumnName("spinner_rank");

                    b.HasKey("Id");

                    b.HasIndex("DraftId", "SelectedClubId")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_teams_draft_club");

                    b.HasIndex("DraftId", "SpinnerRank")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_teams_draft_rank");

                    b.ToTable("draft_teams", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DraftId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_id");

                    b.Property<Guid>("DraftTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("draft_team_id");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid")
                        .HasColumnName("participant_id");

                    b.HasKey("Id");

                    b.HasIndex("DraftTeamId");

                    b.HasIndex("DraftId", "ParticipantId")
                        .IsUnique()
                        .HasDatabaseName("ix_draft_team_members_draft_participant");

                    b.ToTable("draft_team_members", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.EmailOutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("AttemptCount")
                        .HasColumnType("integer")
                        .HasColumnName("attempt_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("kind");

                    b.Property<string>("LastError")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("last_error");

                    b.Property<int>("MaxAttempts")
                        .HasColumnType("integer")
                        .HasColumnName("max_attempts");

                    b.Property<DateTimeOffset>("NextAttemptAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("next_attempt_at");

                    b.Property<string>("Secret")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("secret");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("ToEmail")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("to_email");

                    b.Property<string>("ToName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("to_name");

                    b.HasKey("Id");

                    b.HasIndex("Status", "NextAttemptAt")
                        .HasDatabaseName("ix_email_outbox_status_next_attempt_at");

                    b.ToTable("email_outbox", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.Footballer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Club")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("club");

                    b.Property<string>("CommonName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("common_name");

                    b.Property<Guid>("DatasetVersionId")
                        .HasColumnType("uuid")
                        .HasColumnName("dataset_version_id");

                    b.Property<int>("ExternalId")
                        .HasColumnType("integer")
                        .HasColumnName("external_id");

                    b.Property<string>("FullName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("full_name");

                    b.Property<string>("Height")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("height");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("image_url");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsKickOffEligible")
                        .HasColumnType("boolean")
                        .HasColumnName("is_kick_off_eligible");

                    b.Property<string>("League")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("league");

                    b.Property<string>("Nation")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("nation");

                    b.Property<int>("Overall")
                        .HasColumnType("integer")
                        .HasColumnName("overall");

                    b.Property<string>("PlayStylesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("playstyles_json");

                    b.Property<string>("PreferredFoot")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("preferred_foot");

                    b.Property<string>("PrimaryPosition")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("primary_position");

                    b.Property<string>("RolesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("roles_json");

                    b.Property<int>("SkillMoves")
                        .HasColumnType("integer")
                        .HasColumnName("skill_moves");

                    b.Property<string>("SourceUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("source_url");

                    b.Property<string>("StatsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("stats_json");

                    b.Property<int>("WeakFoot")
                        .HasColumnType("integer")
                        .HasColumnName("weak_foot");

                    b.HasKey("Id");

                    b.HasIndex("DatasetVersionId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_footballers_version_external_id");

                    b.HasIndex("DatasetVersionId", "Overall")
                        .HasDatabaseName("ix_footballers_version_overall");

                    b.ToTable("footballers", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.FootballerPosition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FootballerId")
                        .HasColumnType("uuid")
                        .HasColumnName("footballer_id");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("position");

                    b.HasKey("Id");

                    b.HasIndex("FootballerId");

                    b.HasIndex("Position")
                        .HasDatabaseName("ix_footballer_positions_position");

                    b.ToTable("footballer_positions", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.PasswordResetToken", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("consumed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("token_hash");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("ix_password_reset_tokens_token_hash");

                    b.HasIndex("UserId");

                    b.ToTable("password_reset_tokens", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.PlatformMetadata", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("key");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("value");

                    b.HasKey("Key");

                    b.ToTable("platform_metadata", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.PlayerDatasetVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ActivatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("activated_at");

                    b.Property<int>("ClubCount")
                        .HasColumnType("integer")
                        .HasColumnName("club_count");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("ErrorCount")
                        .HasColumnType("integer")
                        .HasColumnName("error_count");

                    b.Property<int>("FootballerCount")
                        .HasColumnType("integer")
                        .HasColumnName("footballer_count");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("label");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("source");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<int>("WarningCount")
                        .HasColumnType("integer")
                        .HasColumnName("warning_count");

                    b.HasKey("Id");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_player_dataset_versions_status");

                    b.ToTable("player_dataset_versions", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.RosterSlot", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("label");

                    b.Property<int>("Order")
                        .HasColumnType("integer")
                        .HasColumnName("slot_order");

                    b.Property<string>("Position")
                        .HasMaxLength(8)
                        .HasColumnType("character varying(8)")
                        .HasColumnName("position");

                    b.Property<string>("SlotType")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("slot_type");

                    b.Property<Guid>("TemplateId")
                        .HasColumnType("uuid")
                        .HasColumnName("template_id");

                    b.HasKey("Id");

                    b.HasIndex("TemplateId", "Order")
                        .IsUnique()
                        .HasDatabaseName("ix_roster_slots_template_order");

                    b.ToTable("roster_slots", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.RosterTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<int>("PickTimerSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("pick_timer_seconds");

                    b.HasKey("Id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_roster_templates_is_active");

                    b.ToTable("roster_templates", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.SecurityAuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Detail")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("detail");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("ip_address");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("ix_security_audit_events_created_at");

                    b.ToTable("security_audit_events", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AvatarUrl")
                        .HasMaxLength(1024)
                        .HasColumnType("character varying(1024)")
                        .HasColumnName("avatar_url");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email");

                    b.Property<string>("EmailNormalized")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("email_normalized");

                    b.Property<DateTimeOffset?>("InvitationSentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("invitation_sent_at");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("boolean")
                        .HasColumnName("must_change_password");

                    b.Property<DateTimeOffset?>("PasswordChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("password_changed_at");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PreferredTeamName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("preferred_team_name");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("role");

                    b.Property<string>("SecurityStamp")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("security_stamp");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("EmailNormalized")
                        .IsUnique()
                        .HasDatabaseName("ix_users_email_normalized");

                    b.ToTable("users", (string)null);
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.Club", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.PlayerDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DatasetImportIssue", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.PlayerDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftEvent", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.Draft", null)
                        .WithMany("Events")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftParticipant", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.Draft", null)
                        .WithMany("Participants")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftPick", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.Draft", null)
                        .WithMany("Picks")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftRosterSlot", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.Draft", null)
                        .WithMany("Slots")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftTeam", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.Draft", null)
                        .WithMany("Teams")
                        .HasForeignKey("DraftId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftTeamMember", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.DraftTeam", null)
                        .WithMany("Members")
                        .HasForeignKey("DraftTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.Footballer", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.PlayerDatasetVersion", null)
                        .WithMany()
                        .HasForeignKey("DatasetVersionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.FootballerPosition", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.Footballer", null)
                        .WithMany("Positions")
                        .HasForeignKey("FootballerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.PasswordResetToken", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.RosterSlot", b =>
                {
                    b.HasOne("FcDraft.Domain.Entities.RosterTemplate", null)
                        .WithMany("Slots")
                        .HasForeignKey("TemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.Draft", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Participants");

                    b.Navigation("Picks");

                    b.Navigation("Slots");

                    b.Navigation("Teams");
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.DraftTeam", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.Footballer", b =>
                {
                    b.Navigation("Positions");
                });

            modelBuilder.Entity("FcDraft.Domain.Entities.RosterTemplate", b =>
                {
                    b.Navigation("Slots");
                });
#pragma warning restore 612, 618
        }
    }
}
